#!/bin/bash

if [ "$#" -eq 0 ]; then
    mvn -q exec:java -Dexec.mainClass="com.mavenforge.Console.Forge"
else
    args="$@"
    
    mvn -q exec:java -Dexec.mainClass="com.mavenforge.Console.Forge" -Dexec.args="$args"
fi
